name: Push image to JFrog Artifactory

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

env:
  REPOSITORY_URL: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}

jobs:
  build:
    name: Build
    uses: truefoundry/github-workflows-public/.github/workflows/build.yml@v0.1.5
    with:
      image_tag: ${{ github.sha }}
      image_artifact_name: async_processor
      artifactory_registry_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      artifactory_repository_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}
      image_scan_severity_cutoff: critical
    secrets:
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}

  update-chart:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout charts
        uses: actions/checkout@v4
        with:
          repository: truefoundry/infra-charts
          ref: 'main'
          token: ${{ secrets.TF_GITHUB_CI_ADMIN_TOKEN }}
          path: tmp_ahc

      - name: Update truefoundry chart values
        run: |
          sed -i "s|ASYNC_PROCESSOR_SIDECAR_IMAGE:.*|ASYNC_PROCESSOR_SIDECAR_IMAGE: ${{ env.REPOSITORY_URL }}/async_processor:${{ github.sha }}|g" tmp_ahc/charts/truefoundry/values.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: '[CI] Update truefoundry chart values'
          branch: truefoundry-version-${{ github.sha }}
          base: main
          path: tmp_ahc
          title: '[CI] Update truefoundry chart values.yaml - ASYNC_PROCESSOR_SIDECAR_IMAGE'
          token: ${{ secrets.TF_GITHUB_CI_ADMIN_TOKEN }} 
