name: Push image to JFrog Artifactory

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    uses: truefoundry/workflows/.github/workflows/build.yml@v0.2.1
    with:
      image_tag: ${{ github.sha }}
      image_artifact_name: async_processor
      artifactory_registry_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      artifactory_repository_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}
      image_scan_severity_cutoff: critical
    secrets:
      depot_token: ${{ secrets.DEPOT_API_KEY }}
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}
