name: Push image to JFrog Artifactory

on:
  # pull_request:
  #   types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'
      - arm-build

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image
    uses: truefoundry/workflows/.github/workflows/build.yml@main
    secrets: inherit
    with:
      internal: false
